workspace:
  base: /go
  path: src/github.com/readr-media/readr-restful
pipeline:
  unit_test:
    image: golang:1.9.2
    commands:
    - make test
    when:
      event: [pull_request]
      branch: [master, dev]
  
  unit_test_result:
    mage: plugins/slack
    channel: jenkins
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    template: >
      {{#success build.status}}
        Unit test ${DRONE_REPO_NAME} *success*.
      {{else}}
        Houston, we have a problem. Unit test ${DRONE_REPO_NAME} failed. 
      {{/success}}
    when:
      event: [pull_request]
      branch: [master, dev]

  start_slack:
    image: plugins/slack
    channel: jenkins
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    template: >
      *start* building *{{repo.name}}*.
      *{{build.author}}* give *{{build.branch}}* a little push.
    when:
      event: [push]
      branch: [master, dev]

  get_config:
    image: gcr.io/mirrormedia-1470651750304/drone-cloud-sdk:latest
    secrets: [google_credentials]
    commands:
    - gcloud source repos clone default default
    - cp default/readr-restful/main.json config/main.json
    - cp default/readr-restful/newsletter.html config/newsletter.html
    when:
      event: [push]
      branch: [master, dev]

  builds:
    image: golang
    commands:
    - make build-alpine
    when:
      event: [push]
      branch: [master, dev]

  publish:
    image: plugins/gcr
    repo: mirrormedia-1470651750304/${DRONE_REPO_NAME}
    tag: ${DRONE_COMMIT_AUTHOR}_${DRONE_BUILD_NUMBER}
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    secrets: [google_credentials]
    when:
      event: [push]
      branch: [master, dev]

  deploy_dev:
    image: nytimes/drone-gke:develop
    zone: asia-east1-a
    cluster: dev
    namespace: default
    # For debugging
    dry_run: false
    verbose: true
    secrets:
      - source: google_credentials
        target: token
    vars:
      image: gcr.io/mirrormedia-1470651750304/${DRONE_REPO_NAME}:${DRONE_COMMIT_AUTHOR}_${DRONE_BUILD_NUMBER}
      app: readr-rest
      tier: backend
    when:
      event: [push]
      branch: dev
  
  # deploy_prod:
  #   image: nytimes/drone-gke:develop
  #   zone: asia-east1-a
  #   cluster: prod-readr
  #   namespace: default
  #   # For debugging
  #   dry_run: false
  #   verbose: true
  #   secrets:
  #     - source: google_credentials
  #       target: token
  #   vars:
  #     image: gcr.io/mirrormedia-1470651750304/${DRONE_REPO_NAME}:${DRONE_COMMIT_AUTHOR}_${DRONE_BUILD_NUMBER}
  #     app: readr-restful
  #     tier: backend
  #   when:
  #     event: [push]
  #     branch: dev 

  finish_slack:
    image: plugins/slack
    channel: jenkins
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    when:
      status: [success, failure]
      event: [push]
      branch: [master, dev]
    template: >
      {{#success build.status}}
        Build<${DRONE_BUILD_LINK}|#{{build.number}}> *success* ${DRONE_REPO_NAME}:${DRONE_COMMIT_AUTHOR}_${DRONE_BUILD_NUMBER} was well served.
        Check out our new <https://gcr.io/mirrormedia-1470651750304/readr-restful|rest>
      {{else}}
        Houston, we have a problem. Build <${DRONE_BUILD_LINK}|#{{build.number}}> failed. Fix me please, {{build.author}}
      {{/success}}
