ALTER TABLE polls
MODIFY total_vote int(11) NOT NULL DEFAULT 0,
MODIFY updated_at datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


ALTER TABLE polls_choices
MODIFY total_vote int(11) NOT NULL DEFAULT 0,
MODIFY updated_at datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
